version: '3.8'

services:
    # Frontend Service 
  app-client:
    image: thelement012/mockys-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8081/
    ports:
      - "3000:3000"
    depends_on:
      - app-server
    networks:
      - practica2
  # App backend service
  app-server:
    image: thelement012/mockys-backend
    ports:
      - "8081-8083:8081" 
    depends_on: 
      - db 
    environment:
      AMBIENTE: dev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mocki_to
      DB_USER: sa
      DB_PASSWORD: 1234
      APP_NAME: 'mockito'
      APP_PORT: 8081
    networks: 
      - practica2
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=sa
      - POSTGRES_DB=mocky_to
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres.sql:/docker-entrypoint-initdb.d/import.sql
    networks:
      - practica2
      
volumes:
  volumen:

networks:
  practica2:    




