version: '3.8'

services:
    # Frontend Service 
  app-client:
    image: thelement012/mockys-frontend
    environment:
      REACT_APP_API_URL: http://localhost:8081/
    ports:
      - "3000:3000"
    depends_on:
      - app-server
    networks:
      - practica2
  # App backend service
  app-server:
    image: thelement012/mockys-backend
    ports:
      - "8081-8083:8081" 
    depends_on: 
      - db 
    environment:
      AMBIENTE: dev
      DB_HOST: my-sql
      DB_PORT: 3306
      DB_NAME: mocki_to
      DB_USER: root
      DB_PASSWORD: 1234
      APP_NAME: 'mockito'
      APP_PORT: 8081
    networks: 
      - practica2

  # Database Service (H2)
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - volumen:/tmp/
    networks:
      - practica2
      
volumes:
  volumen:

networks:
  practica2:    